name: Publish on push

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install flake8
  - run: pip install mypy
  - run: flake8 run.py roop
  - run: mypy run.py roop
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@master
  - name: Archive Release
    uses: thedoctor0/zip-release@0.7.1
    with:
      type: 'zip'
      filename: 'release.zip'
      exclusions: '*.git* /*node_modules/* .editorconfig'
  - name: Upload Release
    uses: actions/checkout@master
    with:
      artifacts: "release.zip"
      token: ${{ secrets.GH_TOKEN }}